include:
  - project: 'matonto/gitlab-ci'
    ref: master
    file: 'shared-template.yml'

# Can steps 2-5 and steps 6-9 be the same 4 stages just with a variable passed in for the version?
stages:
  - test
  - set_version_root_pom
  - set_version_parent_pom
  - commit_version
  - increment_snapshot_version_root_pom
  - increment_snapshot_version_parent_pom
  - commit_version
  - unit_integration_test

variables:
  ARTIFACTORY_BASE_URL: "https://artifactory.inovexcorp.com/artifactory/"
  MAVEN_SETTINGS_DOCKER: <server>
      <id>docker-hub</id>
      <username>PLACEHOLDER_USERNAME</username>
      <password>PLACEHOLDER_PW</password>
      <configuration>
        <email>PLACEHOLDER_EMAIL</email>
      </configuration>
    </server>

before_script:
  - rm -r /root/.m2/repository && ln -s /opt/m2/repository /root/.m2/repository
  - POM_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout)
  - MAJOR=$(echo $POM_VERSION | cut -d- -f1 | cut -d. -f1)
  - MINOR=$(echo $POM_VERSION | cut -d- -f1 | cut -d. -f2)
  - MICRO=$(echo $POM_VERSION | cut -d- -f1 | cut -d. -f3)
  - ln -s /opt/node_modules $CI_PROJECT_DIR/com.mobi.web/node_modules
  - if [[ "$NEEDS_GIT_SETTINGS" == "1" ]]; then
  -   PRIVATE_URL="$(echo $CI_PROJECT_URL | sed "s|https://|https://gitlab-ci-token:$ACCESS_TOKEN@|g").git"
  -   git remote set-url origin $PRIVATE_URL
  -   git config --global user.email 'gitlab.runner@inovexcorp.com'
  -   git config --global user.name 'Gitlab Runner'
  - fi

# For merge requests, just do an initial test
test:
  variables:
    NEEDS_GIT_SETTINGS: 0
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -pl '!mobi-distribution,!mobi-itests,!:itests-support,!:itests-orm,!:itests-web,!:itests-platform,!:itests-etl,!:itests-rest,!:itests-vfs' test
  except:
    - test-ci
  only:
    - merge_requests

set_version_parent_pom:
  stage: set_version_parent_pom
  only:
    variables:
      - $CI_COMMIT_TITLE =~ /Merge branch .* into 'test-ci'/
    refs:
      - test-ci
  script:
    - CURR_VERSION="$MAJOR.$MINOR.$MICRO"
    - cd mobi-parent && mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$CURR_VERSION && cd ..
  artifacts:
    paths: ['*/pom.xml', 'pom.xml', 'com.mobi.ontology.rest/pom.xml']

increment_snapshot_version_parent_pom:
  stage: increment_snapshot_version_parent_pom
  only:
    variables:
      - $CI_COMMIT_TITLE =~ /Merge branch .* into 'test-ci'/
    refs:
      - test-ci
  script:
    - NEW_VERSION="$MAJOR.$MINOR.$((MICRO+1))"
    - cd mobi-parent && mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$NEW_VERSION-SNAPSHOT && cd ..

# Happens after NON snapshot commit to master
#deploy_rdf_orm:
#  stage: deploy_rdf_orm
#  variables:
#    NEEDS_GIT_SETTINGS: 0
#  only:
#    variables:
#      - $CI_COMMIT_TITLE =~ /^AUTOMATED COMMIT - Updates version to \d+\.\d+\.\d+$/
#    refs:
#      - master
#  script:
#    - cd rdf-orm/rdf-orm-gradle-plugin
#    - ./gradlew publish -Pversion=$MAJOR.$MINOR.$MICRO -PnexusUsername=$NEXUS_USERNAME -PnexusPassword=$NEXUS_PW

# Happens after release tag has been pushed. Deletes the tag, creates new branch based off of the tag name, and updates minor release on master
#update_release:
#  stage: new_release_build
#  only:
#    - tags
#    - /release\/\d+\.\d+/
#  script:
#    - git tag -d $CI_COMMIT_TAG
#    - git push origin :$CI_COMMIT_TAG
#    - git checkout -b $CI_COMMIT_TAG
#    - git push -f origin $CI_COMMIT_TAG
#    - NEW_MASTER_VERSION="$MAJOR.$((MINOR+1)).0-SNAPSHOT"
#    - mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$NEW_MASTER_VERSION
#    - cd mobi-parent && mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$NEW_MASTER_VERSION && cd ..
#    - mvn versions:commit
#    - git add ./\*pom.xml
#    - git commit -m"AUTOMATED RELEASE COMMIT - Updates version to $NEW_MASTER_VERSION"
#    - git push -f origin HEAD:master
#  artifacts:
#    paths:
#      - mobi-distribution

#create_release_branch:
#  stage: create_release_branch
#  only:
#    - tags
#    - /release\/\d+\.\d+/
#  script:
#    - git tag -d $CI_COMMIT_TAG
#    - git push origin :$CI_COMMIT_TAG
#    - git checkout -b $CI_COMMIT_TAG
#    - git push -f origin $CI_COMMIT_TAG

#artifactory_release:
#  stage: new_release_deploy
#  dependencies:
#    - update_release
#  only:
#    - tags
#    - /release\d*\.\d*/
#  script:
#    - mvn $MAVEN_CLI_OPTS clean install -P release-build -DproductId=$GA_KEY
#    - curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PW -X PUT "$ARTIFACTORY_BASE_URL/mobi-binaries/win/mobi-distribution-$MAJOR.$MINOR.$MICRO.zip" -T mobi-distribution/target/mobi-distribution-$MAJOR.$MINOR.$MICRO.zip
#    - curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PW -X PUT "$ARTIFACTORY_BASE_URL/mobi-binaries/nix/mobi-distribution-$MAJOR.$MINOR.$MICRO.tar.gz" -T mobi-distribution/target/mobi-distribution-$MAJOR.$MINOR.$MICRO.tar.gz

# build and push the docker image, per instructions in mobi-distribution README
# tag used to specify we want this job to happen w/ the docker builder runner
#docker_release:
#  stage: new_release_deploy
#  tags:
#    - docker-image-builder
#  dependencies:
#    - update_release
#  only:
#    - tags
#    - /release\d*\.\d*/
#  script:
#    - echo $MAVEN_SETTINGS_DOCKER | sed -e "s/PLACEHOLDER_USERNAME/$DOCKER_USERNAME/" -e "s/PLACEHOLDER_PW/$DOCKER_PW/" -e "s/PLACEHOLDER_EMAIL/$DOCKER_EMAIL/" > /root/.m2/ci_settings.xml
#    - cd mobi-distribution
#    - mvn $MAVEN_CLI_OPTS docker:build -DpushImageTag -s /root/.m2/ci_settings.xml

