version: '2'
services:
  mobi:
    container_name: Mobi
    image: mobi:${project.version}
    build: .
    ports:
      - "8443:8443"
    command: bash -c '/opt/mobi/distribution-${project.version}/bin/karaf'
